[package]
name = "rust-loguru"
version = "0.1.0"
edition = "2021"
authors = ["Jayasimha Raghavan <mr.jayasimha@gmail.com>"]
description = "A flexible and extensible logging library for Rust, inspired by Python's Loguru"
license = "MIT"
repository = "https://github.com/j-raghavan/rust-loguru"
documentation = "https://docs.rs/rust-loguru"
readme = "README.md"
keywords = ["logging", "log", "logger", "loguru"]
categories = ["development-tools", "development-tools::debugging"]
exclude = ["specs/", "*.log", "bench"]

[dependencies]
lazy_static = "1.4.0"
parking_lot = "0.12"
chrono = "0.4"
thiserror = "1.0.50"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.0"
rand = "0.8"

[dev-dependencies]
criterion = "0.5"
tempfile = "3.8"

[features]
default = []
json = []
colors = ["colored"]

[[example]]
name = "api_usage"
path = "examples/api_usage.rs"

[[example]]
name = "advanced_usage"
path = "examples/advanced_usage.rs"

[[bench]]
name = "logging_bench"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]