name: Release

on:
  push:
    tags:
      - "v[0-9]+.*"

permissions:
  contents: write
  pages: write      # Added for GitHub Pages deployment

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  verify:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

  create-release:
    name: Create GitHub Release
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true

  publish-crate:
    name: Publish to crates.io
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Verify Cargo.toml is complete
        run: |
          if ! grep -q "description" Cargo.toml; then
            echo "Cargo.toml is missing 'description' field"
            exit 1
          fi
          if ! grep -q "license" Cargo.toml; then
            echo "Cargo.toml is missing 'license' field"
            exit 1
          fi
          if ! grep -q "repository" Cargo.toml; then
            echo "Cargo.toml is missing 'repository' field"
            exit 1
          fi

      - name: Check publish is possible
        run: cargo publish --dry-run --allow-dirty

      - name: Publish crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_KEY }}
        run: cargo publish --allow-dirty
        
  build-docs:
    name: Build and Publish Documentation
    needs: publish-crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build documentation
        run: cargo doc --no-deps --document-private-items

      - name: Determine crate name for documentation
        id: crate_name
        run: |
          CRATE_NAME=$(grep -m 1 "name" Cargo.toml | cut -d '"' -f 2 | tr '-' '_')
          echo "CRATE_NAME=${CRATE_NAME}" >> $GITHUB_ENV
          echo "Crate name: ${CRATE_NAME}"

      - name: Create index.html redirect
        run: |
          echo '<meta http-equiv="refresh" content="0; url=${{ env.CRATE_NAME }}/index.html">' > target/doc/index.html
          cat target/doc/index.html

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./target/doc

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2